import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useTasksContext } from '../context/TasksProvider'
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import CardActions from '@material-ui/core/CardActions';

import AddTask from './components/AddTask'
import TaskList from './components/TaskList'

const Home: NextPage = () => {
  const { availableTaskList, finishedTaskList } = useTasksContext()
  const totalTasks = availableTaskList.length + finishedTaskList.length
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Todo <span>App</span>
        </h1>

        <p className={styles.description}>
          Let&apos;s get it done!
        </p>

        <Card variant="outlined">
          <CardContent>
            <AddTask />
            <TaskList />
          </CardContent>
          <CardActions>
            <strong><small>Total: { totalTasks }</small></strong><br />
            <small>Finished Tasks: { finishedTaskList.length }</small>
          </CardActions>
        </Card>
      </main>
    </div>
  )
}

export default Home
